# Generated by Django 3.0.9 on 2020-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='scope',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('ae', 'ae'), ('se', 'se'), ('sl', 'sl'), ('bh', 'bh')], default='user', max_length=16),
        ),
    ]
