# Generated by Django 3.0.9 on 2020-09-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='model_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
