# Generated by Django 3.0.9 on 2020-09-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_model_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
