# Generated by Django 3.0.9 on 2020-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201008_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='electrical',
            field=models.CharField(default='230V-1Ph-60Hz', max_length=20),
        ),
    ]
