# Generated by Django 3.0.9 on 2020-10-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201015_0923'),
        ('products', '0011_product_electrical'),
    ]

    operations = [
    ]
