# Generated by Django 3.0.9 on 2020-09-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
