# Generated by Django 3.0.9 on 2020-09-20 08:51

import aqa.quotations.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_quotation_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=aqa.quotations.models.quote_duration, null=True),
        ),
    ]
