# Generated by Django 3.0.9 on 2020-09-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_quotationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='expiry_date',
        ),
    ]
