# Generated by Django 3.0.9 on 2020-10-08 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_auto_20200924_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
