# Generated by Django 3.0.9 on 2020-10-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0023_auto_20201013_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='author',
            new_name='authorss',
        ),
    ]
