# Generated by Django 3.0.9 on 2020-10-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0024_auto_20201013_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='authorss',
        ),
        migrations.AddField(
            model_name='quotation',
            name='author',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
