# Generated by Django 3.0.9 on 2020-10-19 15:39

import aqa.quotations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0026_auto_20201013_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='expiry_date',
            field=models.DateField(default=aqa.quotations.models.quote_duration),
        ),
        migrations.AddField(
            model_name='quotation',
            name='location',
            field=models.CharField(default='Metro Manila', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(default='Full payment before delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sub_subject',
            field=models.CharField(default='Supply and Delivery of Air Conditioning Units', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(default=models.CharField(max_length=50, null=True), max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='application_engr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_as_ae', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations_as_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sales_engr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_as_se', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sales_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_as_sl', to=settings.AUTH_USER_MODEL),
        ),
    ]
