# Generated by Django 3.0.9 on 2020-10-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0027_auto_20201019_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
