# Generated by Django 3.0.9 on 2020-10-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0028_auto_20201019_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='subject',
        ),
    ]
