# Generated by Django 3.0.9 on 2020-10-19 16:08

import aqa.quotations.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0031_auto_20201019_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='expiry_date',
            field=models.DateTimeField(default=aqa.quotations.models.quote_duration),
        ),
    ]
