# Generated by Django 3.0.9 on 2020-10-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0033_auto_20201020_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
