# Generated by Django 3.0.9 on 2020-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0034_auto_20201023_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
