# Generated by Django 3.0.9 on 2020-10-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0037_auto_20201023_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='quotations.Quotation'),
            preserve_default=False,
        ),
    ]
