# Generated by Django 3.0.9 on 2020-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0043_remove_quotation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='lead_time',
            field=models.CharField(default='30-45 days', max_length=100),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='tagging',
            field=models.CharField(default='FCU/ACCU', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='line_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
