# Generated by Django 3.0.9 on 2020-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0044_auto_20201025_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='tagging',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
