# Generated by Django 3.0.9 on 2020-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201008_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='Description', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(default='Model Name', max_length=30),
            preserve_default=False,
        ),
    ]
