# Generated by Django 3.0.9 on 2020-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201008_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
