# Generated by Django 3.0.9 on 2020-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_20201027_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
