# Generated by Django 3.0.9 on 2020-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_auto_20200920_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
