# Generated by Django 3.0.9 on 2020-10-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_remove_quotationitem_line_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
