# Generated by Django 3.0.9 on 2020-10-13 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0022_auto_20201013_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorsss', to=settings.AUTH_USER_MODEL),
        ),
    ]
