# Generated by Django 3.0.9 on 2020-10-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0029_remove_quotation_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
