# Generated by Django 3.0.9 on 2020-10-19 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0030_quotation_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
