# Generated by Django 3.0.9 on 2020-10-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0032_auto_20201019_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='modified_by',
            new_name='last_modified',
        ),
    ]
