# Generated by Django 3.0.9 on 2020-10-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0039_auto_20201023_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
    ]
