# Generated by Django 3.0.9 on 2020-10-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0040_remove_quotationitem_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.Quotation'),
        ),
    ]
