# Generated by Django 3.0.9 on 2020-10-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0042_auto_20201024_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_price',
        ),
    ]
