# Generated by Django 3.0.9 on 2020-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0045_auto_20201025_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='project',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='tagging',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
