# Generated by Django 3.0.9 on 2020-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201025_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
